version: '4.28'
services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  api:
    build: .
    ports:
      - 3000:3000
    environment:
      HOST: '127.0.0.1'
      PORT: 3000
      MONGO_URI: 
    depends_on:
      - mongo_db
volumes:
  mongo_db: {}

