version: "4"
services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  api:
    build: .
    ports:
      - 4000:3000
    environment:
      HOST: "127.0.0.1"
      PORT: 3000
      MONGO_URI: mongodb+srv://songs:songs65431@atlascluster.f6fmcgs.mongodb.net/songs?retryWrites=true&w=majority
    depends_on:
      - mongo_db
volumes:
  mongo_db: {}
