
version: "4"

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest  # Or use a specific version for consistency
    restart: always
    volumes:
      - mongo-data:/data/db  # Optional persistent data volume

  api:
    build: .  # Build from the current directory
    ports:
      - "4000:3000"  # Dynamic port mapping (optional)
    environment:
      HOST: "0.0.0.0"  # Listen on all interfaces
      PORT: 3000
      MONGO_URI: "${MONGO_URI}"  # Placeholder for environment variable
    depends_on:
      - mongo_db

volumes:
  mongo-data: {}  # Optional volume for persistent data

